version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: exam_manager
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - exam_manager_db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DB_URL: "jdbc:mysql://db:3306/exam_manager"
      DB_USER: "your_username"
      DB_PASSWORD: "your_password"
    command: sbt run

volumes:
  db_data:
