version: '3.9'
services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: exam_manager
            MYSQL_USER: your_username
            MYSQL_PASSWORD: your_password
        ports:
            - "3306:3306"
        volumes:
            - exam_manager_db_data_prod:/var/lib/mysql

    app:
        build: .
        command: sbt run
        environment:
            DB_URL: "jdbc:mysql://db:3306/exam_manager"
            DB_USER: "your_username"
            DB_PASSWORD: "your_password"
        ports:
            - "9000:9000"
        depends_on:
            - db

volumes:
    exam_manager_db_data_prod:
