version: '3.9'
services:
  app:
    container_name: exam-manager-devapp
    build:
      context: ..
      dockerfile: localEnv/Dockerfile
    ports:
      - "9010:9000"
    depends_on:
      - db
    environment:
      DB_URL: "jdbc:mysql://db:3306/exam_manager"
      DB_USER: "your_username"
      DB_PASSWORD: "your_password"
    command: sbt run

  db:
    container_name: exam-manager-devdb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: exam_manager
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3310:3306"
    volumes:
      - exam_manager_db_data_dev:/var/lib/mysql

volumes:
  exam_manager_db_data_dev:
